name: Terraform Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-north-1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Terraform init
        run: terraform init

      - name: Terraform format
        run: terraform fmt

      - name: Terraform format check
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-check
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-north-1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Terraform init
        run: terraform init

      - name: Create Terraform variable file
        run: |
          echo 'aws_private_key = <<EOF' > terraform.tfvars
          echo "${{ secrets.AWS_PRIVATE_KEY }}" >> terraform.tfvars
          echo 'EOF' >> terraform.tfvars

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars" -out=tfplan -input=false

      - name: Save Terraform Plan
        run: terraform show -json tfplan > tfplan.json

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan.json

      - name: Clean up variable file
        run: rm terraform.tfvars

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-north-1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Terraform init
        run: terraform init

      - name: Create Terraform variable file
        run: |
          echo 'aws_private_key = <<EOF' > terraform.tfvars
          echo "${{ secrets.AWS_PRIVATE_KEY }}" >> terraform.tfvars
          echo 'EOF' >> terraform.tfvars

      - name: Terraform Apply
        run: terraform apply -var-file="terraform.tfvars" -auto-approve  

      - name: Show Terraform Outputs
        run: terraform output

      - name: Clean up variable file
        run: rm terraform.tfvars
