name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::571600867782:role/GitHubActionsRole
          aws-region: us-east-1
          role-session-name: GitHubActionsSession

      - name: List S3 buckets
        run: aws s3 ls
        
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.assume-role.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.assume-role.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.assume-role.outputs.aws-session-token }}
