name: Terraform Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-north-1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Terraform init
        run: terraform init

      - name: Terraform format
        run: terraform fmt

      - name: Terraform validate
        run: terraform validate

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-check
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-north-1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-north-1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve

      - name: Terraform output after apply
        id: outputs
        run: terraform output -json > outputs.json

      - name: Generate resource graph
        run: |
          terraform graph > graph.dot
          dot -Tpng graph.dot -o graph.png

      - name: Terraform destroy
        run: terraform destroy -auto-approve
