name: Base Infrastructure Deployment

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform-infra-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-north-1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Terraform init
        run: terraform init

      - name: Save private key to file
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Terraform Plan
        run: |
          export TF_VAR_aws_private_key=$(cat ~/.ssh/id_rsa)
          terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Save Infrastructure Outputs
        run: terraform output -json > infra_outputs.json

      - name: Upload Infrastructure Outputs
        uses: actions/upload-artifact@v3
        with:
          name: infra_outputs
          path: infra_outputs.json
